title: "Measure-Theoretic Probability Notes"
baseurl: "" # leave empty for user.github.io/repo/
url: ""     # GitHub Pages will fill this in
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
